### PR TITLE
Added border for search button for consistent styling

### PR DESCRIPTION
**Pull request by amb8805**
for issue #87

### CODE REVIEW

**Comment by mok4ry** [comment]
Are we okay with the color of the search button text? I feel like we never explicitly set it, and I'm not quite in love with it. I also feel like this PR is a good place for that change to happen.

screen shot 2016-04-17 at 11 04 05 pm

**Comment by amb8805** [comment]
I personally thing its okay. I played around with a lot of possible options for the search color etc, and i think it lets it stand out a bit.  I'm not in love with it, but I like it more than the black one.

**Comment by lukecoy** [comment]
I'm not a UI person, we should / could ask Ricardo.. but I think the red font isn't really the color we're looking for. That makes the search seem like some sort of "Are you sure you want to do this?" action, similar to when you're deleting a repo from GitHub. It's just a search.

**Comment by jmp3833** [comment]
LGTM :+1:

**Pull request merged**
