### PR TITLE
Results page input

### PR DESCRIPTION
**Pull request by mok4ry**
Add ability to search from results page query input. Also add unit tests for custom JS utilities (including the query builder).

### CODE REVIEW

**Comment by mok4ry** [comment]
Issue #96

**Comment by lukecoy** [comment]
@mok4ry and I talked about this, and decided it would be best to put this on the backburner for now. We can kind of iterate over this story by providing a "filter results" button that redirects to a filled-out home page. Then we can readdress this. @mok4ry can you make an issue?

**Comment by mok4ry** [comment]
Yeah, issue #101

**Comment by mok4ry** [comment]
Going to close this PR for now, but leave the branch for future work.

**Pull request closed without merging**
