### PR TITLE
moved pagination into results UL for fomatting

### PR DESCRIPTION
**Pull request by amb8805**
Moved Pagination into Results UL and appended as last LI so that it is always displayed at the end of the results page

### CODE REVIEW

**Comment by lukecoy** [comment]
much better :) waiting for travis

**Comment by amb8805** [comment]
so now that everything works again can we merge this potentially?

**Comment by amb8805** [comment]
@lukecoy travis should pass now that react is installing correctly again

**Comment by lukecoy** [comment]
oh okay we'll see if that NPM issue resolved itself

**Pull request merged**
